services:
  ##
  api:
    tty: true
    privileged: true
    stdin_open: true
    build:
      context: .
    volumes:
      - ./reports:/var/www/project/reports
      - .:/var/www/project
    env_file:
      - ./test.env
    depends_on:
      rabbit:
        condition: service_healthy

  ##
  rabbit:
    image: rabbitmq:3-management
    tty: true
    privileged: true
    stdin_open: true
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./test.env
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
